### ISSUE TITLE
Won't Check

### ISSUE THREAD

**Issue by 3jm** [Digneety/UplayName#3]
**Describe the bug**
I put the usernames I want to check in the names.txt file, I have dotNet 5.0 installed, i run the exe and nothing happens, just says checking without proxies 

**To Reproduce**
1. put names in names.txt
2. run the exe
3. nothing happens

**Expected behavior**
the names to be checked

**Screenshots**
https://cdn.discordapp.com/attachments/1002496933883031603/1003518251403321414/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Chrome
 - Latest

**Comment by userdignity** [comment]
Could you please post a picture with the exe and the names.txt file next to each other?

**Comment by 3jm** [comment]
just stays open still, nothing happening. dotNet 5.0.17 is installed

![image](https://user-images.githubusercontent.com/68416923/182421622-5ae4fddb-6aa1-46ac-91d0-6a4117d834b5.png)

**Comment by userdignity** [comment]
Can't reproduce the issue till today. Do you have an IDE installed?

**Comment by 3jm** [comment]
visual studio code

**Comment by userdignity** [comment]
I'd say try cloning the repository and compiling the project as it is yourself.

**Comment by 3jm** [comment]
cloned the repo and built it with no issues, checked netlimiter to see if its making requests and it is not, is it working for you?

![image](https://user-images.githubusercontent.com/68416923/183775673-e494cadc-3697-4d71-a85f-e130fb30fa9d.png)

**Comment by userdignity** [comment]
I released a newer and improved version try if it works now.
