### ISSUE TITLE
Unhandeled Exception Problem 

### ISSUE THREAD

**Issue by jonas04-hm** [Digneety/UplayName#4]
Describe the bug
I put the usernames I want to check in the names.txt file, I have dotNet 5.0 installed, i run the exe then press enter. This happens 

To Reproduce

put names in names.txt
run the exe
press enter
this happens 

Expected behavior
the names to be checked

Desktop 

OS: Windows 11 21H2
Chrome 
Latest

![Screenshot_3](https://user-images.githubusercontent.com/33195933/183318178-1a736aba-913e-4233-b626-ac708ad80e65.jpg)

**Comment by userdignity** [comment]
Does your Ubisoft account have 2fa enabled?
